config/routes.rb
SearchEngines::Application.routes.draw do
  root :to => 'results#index', :as => :results
end

app/models/goof.rb
class Goof < ActiveRecord::Base
  attr_accessible :goof_type, :movie_id, :description
  belongs_to :movie

  searchable do
    text :description
    text :goof_type
  end

  def self.text_search(query)
    where("description @@ :q or goof_type @@ :q", q: query).limit(15)
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :name, :year
  has_many :goofs
end

app/models/my_goof.rb
class MyGoof < ActiveRecord::Base
  attr_accessible :goof_type, :my_movie_id, :description
  belongs_to :my_movie

  establish_connection(
    :adapter  => "mysql2",
    :host     => "localhost",
    :username => "root",
    :database => "search_engines"
  )
end

app/models/my_movie.rb
class MyMovie < ActiveRecord::Base
  attr_accessible :name, :year

  establish_connection(
    :adapter  => "mysql2",
    :host     => "localhost",
    :username => "root",
    :database => "search_engines"
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    if params[:search].present?
      @results = Goof::ThinkingSphinx.search params[:search],
                              :max_matches => 15,
                              :per_page    => 15

      standart_search = Sunspot.search(Goof) do
        fulltext params[:search]
        paginate :page => 1, :per_page => 15
      end

      @solr_time = standart_search.query_time / 1000.0
      @solr_results = standart_search.results

      @pstg_results = Goof.text_search params[:search]

      @mysql_results = MyGoof.find(:all, :conditions => ["match(description,goof_type) against (? IN BOOLEAN MODE)", params[:search]]).first 15
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SearchEngines" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div>

    <!--<%= javascript_include_tag "application" %>-->

  </body>
</html>

app/views/results/index.html.erb
<h1><%= "Search Engines" %></h1>

<%= form_tag results_path, :method => :get do %>
  <div id="search">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, :class => "btn" %>
  </div>
<% end %>
<div class="row">
  <div class="span3">
    <% if @results %>
      <h5><%= "Sphinx search took #{@results.query_time} seconds ans return the following results:" %></h5></br>
      <ul>
        <% @results.each do |result| %>
          <li class="search_result">
            <div class="movie_name">
              <h3><%= result.movie.name %>
              (<%= result.movie.year %>)</h3>
            </div>
            <div class="description">
              <%= result.description %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="span3">
    <% if @solr_results %>
      <h5><%= "Solr search took #{@solr_time} seconds ans return the following results:" %></h5></br>
      <ul>
        <% @solr_results.each do |result| %>
          <li class="search_result">
            <div class="movie_name">
              <h3><%= result.movie.name.html_safe %>
              (<%= result.movie.year %>)</h3>
            </div>
            <div class="description">
              <%= result.description.html_safe %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="span3">
    <% if @pstg_results %>
      <h5><%= "Postgres Search return the following results:" %></h5></br>
      <ul>
        <% @pstg_results.each do |result| %>
          <li class="search_result">
            <div class="movie_name">
              <h3><%= result.movie.name.html_safe %>
              (<%= result.movie.year %>)</h3>
            </div>
            <div class="description">
              <%= result.description.html_safe %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="span3">
    <% if @mysql_results %>
      <h5><%= "MySQL Search return the following results:" %></h5></br>
      <ul>
        <% @mysql_results.each do |result| %>
          <li class="search_result">
            <div class="movie_name">
              <h3><%= result.my_movie.name.html_safe %>
              (<%= result.my_movie.year %>)</h3>
            </div>
            <div class="description">
              <%= result.description.html_safe %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>